parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'

    App\Infrastructure\Telegram\TelegramClient:
        arguments:
            $token: '%env(TELEGRAM_BOT_TOKEN)%'
